Add cat photo app
OMOTAYO05/01-fcc-cat-photo-app pull request #1
Opened 2024-08-16 09:07 UTC by OMOTAYO05

# A cat photo app

2024-09-02 07:37 UTC, teckcipher requested changes
There are few things left to do, you can check out Azeezat's PR to catch up with some of the suggested changes.
Aside from the below comments, your README should include the demo/deploy link of the app, the correct github repo of this app  for cloning instruction and your details in the author section.

2024-09-02 07:37 UTC, teckcipher commented on README.md
> +![01-fcc-cat-photo-app](https://cdn.freecodecamp.org/curriculum/cat-photo-app/relaxing-cat.jpg)
The link should be your app screenshot not a photo of a cat.

2024-09-02 07:37 UTC, teckcipher commented on README.md
>  # Project Name
Let's add the name of the project here.

2024-09-02 07:37 UTC, teckcipher commented on README.md
> +- Github Action
Can we add link for [Github Action](https://docs.github.com/en/actions)? We should also add [Vercel](https://vercel.com).

2024-09-03 16:26 UTC, Gbemisola19 commented on README.md
> +# 01-FCC-CAT-PHOTO-APP
Can you remove the '01' and 'underscore'

2024-09-03 16:26 UTC, Gbemisola19 commented on README.md
> +> A CAT PHOTO APP BUILT USING HTML.
since it is not an heading, it would look better if you  change the sentence  to a lower case

2024-09-03 16:26 UTC, Gbemisola19 commented on README.md
> +![01-fcc-cat-photo-app](app_screenshot.png)
Can we just leave it as cat photo app?

2024-09-03 16:26 UTC, Gbemisola19 commented on README.md
> +> A CAT PHOTO APP BUILT USING HTML.
There is no need for space between your project name and statement about the project

2024-09-15 06:05 UTC, merged